spring.application.name=SpringBoot_web
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:C:/Users/rajra/OneDrive/Documents/Spring_data/Spring_jdbc
spring.datasource.username=raj
spring.datasource.password=Demo@123  
spring.jpa.hibernate.ddl-auto=update
